force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the supplier is located.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/test/SuppliersSelectorTest.cls
/**
 * Created by dmitrychausov on 30/05/2022.
 */

@IsTest
private class SuppliersSelectorTest {

    @IsTest
    private static void selectByCityTest() {
        Supplier__c supp = new Supplier__c(Name = 'Poznan', City__c = 'Poznan', Location__Latitude__s = 10, Location__Longitude__s = 10);
        insert supp;
        List<Supplier__c> suppliers =
                SuppliersSelector.newInstance().selectByCity(new Set<String> { supp.City__c });
        System.assertEquals(supp.City__c, suppliers[0].City__c, 'City should be equals');
    }

}